name: Update dependency graph

on:
  pull_request:

permissions:
  contents: write

jobs:
  update-dependency-graph:
    runs-on: [self-hosted, zendesk-stable]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.7.0

        with:
          distribution: 'corretto'
          java-version: '17'
