name: Update dependency graph

on:
  push:
    branches: [ 'master' ]

permissions:
  contents: write

jobs:
  update-dependency-graph:
    runs-on: [self-hosted, zendesk-stable]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.7.0

        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Fix maven-repo.gradle
        run: |
          # Display content of the problematic file
          echo "Current content of maven-repo.gradle:"
          cat gradle/maven-repo.gradle
          
          # Create a temporary file with fixes
          cat > gradle/maven-repo.gradle.new << 'EOL'
          // Define the property as an extension property
          ext {
              baseMavenRepoAllUrl = System.getenv('BASE_MAVEN_REPO_ALL_URL') ?: "https://zdrepo.jfrog.io/zdrepo/zen-libs-m2/"
          }
          
          // Rest of the original file content can follow
          // ... keep any other needed content from the original file
          EOL
          
          # Replace the original file
          mv gradle/maven-repo.gradle.new gradle/maven-repo.gradle
          
          # Verify the change
          echo "Updated content of maven-repo.gradle:"
          cat gradle/maven-repo.gradle

      - name: Print Gradle info
        run: |
          ./gradlew --version
          ./gradlew properties

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4.3.0
        with:
          gradle-build-root: .
          gradle-build-module: .
          gradle-build-configuration: implementation
